<?xml version='1.0' encoding='UTF-8'?>
<WL5G3N0:definitions name="SmsBalanceadoService" targetNamespace="http://ws.sms.bice.cl/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://ws.sms.bice.cl/" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://ws.sms.bice.cl/" schemaLocation="smsBalanceado_SCHEMA_2FPORTAL_2FSMS_2FXMLSchema_1180819779.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="enviarSMS">
    <WL5G3N0:part element="WL5G3N1:enviarSMS" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="enviarSMSResponse">
    <WL5G3N0:part element="WL5G3N1:enviarSMSResponse" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="recargaBalanceoSMS">
    <WL5G3N0:part element="WL5G3N1:recargaBalanceoSMS" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="recargaBalanceoSMSResponse">
    <WL5G3N0:part element="WL5G3N1:recargaBalanceoSMSResponse" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="SmsBalanceado">
    <WL5G3N0:operation name="enviarSMS">
      <WL5G3N0:input message="WL5G3N1:enviarSMS"/>
      <WL5G3N0:output message="WL5G3N1:enviarSMSResponse"/>
    </WL5G3N0:operation>
    <WL5G3N0:operation name="recargaBalanceoSMS">
      <WL5G3N0:input message="WL5G3N1:recargaBalanceoSMS"/>
      <WL5G3N0:output message="WL5G3N1:recargaBalanceoSMSResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="SmsBalanceadoPortBinding" type="WL5G3N1:SmsBalanceado">
    <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="enviarSMS">
      <WL5G3N2:operation/>
      <WL5G3N0:input>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
    <WL5G3N0:operation name="recargaBalanceoSMS">
      <WL5G3N2:operation/>
      <WL5G3N0:input>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="SmsBalanceadoService">
    <WL5G3N0:port binding="WL5G3N1:SmsBalanceadoPortBinding" name="SmsBalanceadoPort">
      <WL5G3N2:address location="http://edusa:8011/PORTAL/SMS/smsBalanceado"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>