package cl.ares.bice.ws.enviosms.ws.proxy;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class SmsBalanceadoPortClient {
    public static void main(String[] args) {
        SmsBalanceadoService smsBalanceadoService = new SmsBalanceadoService();
        //SmsBalanceado smsBalanceado = smsBalanceadoService.getSmsBalanceadoPort();
        // Add your code to call the desired methods.


    }
}
