
package cl.ares.bice.ws.enviosms.ws.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import cl.ares.bice.ws.enviosms.ws.types.EnviaSmsRespTO;
import cl.ares.bice.ws.enviosms.ws.types.EnviaSmsTO;
import cl.ares.bice.ws.enviosms.ws.types.ObjectFactory;
import cl.ares.bice.ws.enviosms.ws.types.RecargaBalanceoRespTO;
import cl.ares.bice.ws.enviosms.ws.types.RecargaBalanceoTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SmsBalanceado", targetNamespace = "http://ws.sms.bice.cl/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SmsBalanceado {


    /**
     *
     * @param request
     * @return
     *     returns cl.ares.bice.ws.enviosms.ws.types.EnviaSmsRespTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviarSMS", targetNamespace = "http://ws.sms.bice.cl/",
                    className = "cl.ares.bice.ws.enviosms.ws.types.EnviarSMS")
    @ResponseWrapper(localName = "enviarSMSResponse", targetNamespace = "http://ws.sms.bice.cl/",
                     className = "cl.ares.bice.ws.enviosms.ws.types.EnviarSMSResponse")
    public EnviaSmsRespTO enviarSMS(@WebParam(name = "request", targetNamespace = "") EnviaSmsTO request);

    /**
     *
     * @param request
     * @return
     *     returns cl.ares.bice.ws.enviosms.ws.types.RecargaBalanceoRespTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recargaBalanceoSMS", targetNamespace = "http://ws.sms.bice.cl/",
                    className = "cl.ares.bice.ws.enviosms.ws.types.RecargaBalanceoSMS")
    @ResponseWrapper(localName = "recargaBalanceoSMSResponse", targetNamespace = "http://ws.sms.bice.cl/",
                     className = "cl.ares.bice.ws.enviosms.ws.types.RecargaBalanceoSMSResponse")
    public RecargaBalanceoRespTO recargaBalanceoSMS(@WebParam(name = "request", targetNamespace = "")
                                                    RecargaBalanceoTO request);

}
