//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:28:23 PM GMT 
//


package cl.ares.bice.seguridad.sfa.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoordenadaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoordenadaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Fila" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Columna" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoordenadaType", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", propOrder = {
    "fila",
    "columna"
})
public class CoordenadaType {

    @XmlElement(name = "Fila", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas")
    protected int fila;
    @XmlElement(name = "Columna", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", required = true)
    protected String columna;

    /**
     * Gets the value of the fila property.
     * 
     */
    public int getFila() {
        return fila;
    }

    /**
     * Sets the value of the fila property.
     * 
     */
    public void setFila(int value) {
        this.fila = value;
    }

    /**
     * Gets the value of the columna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumna() {
        return columna;
    }

    /**
     * Sets the value of the columna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumna(String value) {
        this.columna = value;
    }

}
