//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:28:23 PM GMT 
//


package cl.ares.bice.seguridad.sfa.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoordenadasType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoordenadasType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Coordenada" type="{http://www.bice.cl/bice-ws/seguridad/desafio/schemas}CoordenadaType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoordenadasType", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", propOrder = {
    "coordenada"
})
public class CoordenadasType {

    @XmlElement(name = "Coordenada", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", required = true)
    protected List<CoordenadaType> coordenada;

    /**
     * Gets the value of the coordenada property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordenada property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordenada().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordenadaType }
     * 
     * 
     */
    public List<CoordenadaType> getCoordenada() {
        if (coordenada == null) {
            coordenada = new ArrayList<CoordenadaType>();
        }
        return this.coordenada;
    }

}
