//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:28:23 PM GMT 
//


package cl.ares.bice.seguridad.sfa.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DesafioListadoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DesafioListadoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoDesafio" type="{http://www.bice.cl/bice-ws/seguridad/desafio/schemas}TipoDesafioType"/>
 *         &lt;element name="Identificador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Grupo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DesafioListadoType", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", propOrder = {
    "tipoDesafio",
    "identificador",
    "grupo"
})
public class DesafioListadoType {

    @XmlElement(name = "TipoDesafio", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", required = true)
    protected TipoDesafioType tipoDesafio;
    @XmlElement(name = "Identificador", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", required = true)
    protected String identificador;
    @XmlElement(name = "Grupo", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", required = true)
    protected String grupo;

    /**
     * Gets the value of the tipoDesafio property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDesafioType }
     *     
     */
    public TipoDesafioType getTipoDesafio() {
        return tipoDesafio;
    }

    /**
     * Sets the value of the tipoDesafio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDesafioType }
     *     
     */
    public void setTipoDesafio(TipoDesafioType value) {
        this.tipoDesafio = value;
    }

    /**
     * Gets the value of the identificador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificador() {
        return identificador;
    }

    /**
     * Sets the value of the identificador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificador(String value) {
        this.identificador = value;
    }

    /**
     * Gets the value of the grupo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrupo() {
        return grupo;
    }

    /**
     * Sets the value of the grupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrupo(String value) {
        this.grupo = value;
    }

}
