//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:29:09 PM GMT 
//


package cl.ares.bice.seguridad.sfa.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstaTelefonoRegistradoResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstaTelefonoRegistradoResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Estado" type="{http://www.bice.cl/sms}EstadoSmsType"/>
 *         &lt;element name="EstaRegistrado" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstaTelefonoRegistradoResponseType", namespace = "http://www.bice.cl/sms", propOrder = {
    "estado",
    "estaRegistrado"
})
public class EstaTelefonoRegistradoResponseType {

    @XmlElement(name = "Estado", namespace = "http://www.bice.cl/sms", required = true)
    protected EstadoSmsType estado;
    @XmlElement(name = "EstaRegistrado", namespace = "http://www.bice.cl/sms")
    protected Boolean estaRegistrado;

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoSmsType }
     *     
     */
    public EstadoSmsType getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoSmsType }
     *     
     */
    public void setEstado(EstadoSmsType value) {
        this.estado = value;
    }

    /**
     * Gets the value of the estaRegistrado property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEstaRegistrado() {
        return estaRegistrado;
    }

    /**
     * Sets the value of the estaRegistrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEstaRegistrado(Boolean value) {
        this.estaRegistrado = value;
    }

}
