//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 08:10:19 PM GMT 
//


package cl.ares.bice.seguridad.sfa.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.bice.seguridad.sfa.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EliminaRegistroUsuarioRequest_QNAME = new QName("http://www.bice.cl/sms", "EliminaRegistroUsuarioRequest");
    private final static QName _RegistrarUsuarioRequest_QNAME = new QName("http://www.bice.cl/sms", "RegistrarUsuarioRequest");
    private final static QName _EstaTelefonoRegistradoResponse_QNAME = new QName("http://www.bice.cl/sms", "EstaTelefonoRegistradoResponse");
    private final static QName _ObtenerCelularResponse_QNAME = new QName("http://www.bice.cl/sms", "ObtenerCelularResponse");
    private final static QName _RegistrarUsuarioResponse_QNAME = new QName("http://www.bice.cl/sms", "RegistrarUsuarioResponse");
    private final static QName _EliminaRegistroUsuarioResponse_QNAME = new QName("http://www.bice.cl/sms", "EliminaRegistroUsuarioResponse");
    private final static QName _EstaTelefonoRegistradoRequest_QNAME = new QName("http://www.bice.cl/sms", "EstaTelefonoRegistradoRequest");
    private final static QName _EnviarSmsResponse_QNAME = new QName("http://www.bice.cl/sms", "EnviarSmsResponse");
    private final static QName _ObtenerCelularRequest_QNAME = new QName("http://www.bice.cl/sms", "ObtenerCelularRequest");
    private final static QName _EnviarSmsRequest_QNAME = new QName("http://www.bice.cl/sms", "EnviarSmsRequest");
    private final static QName _ListarDesafiosRequest_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "ListarDesafiosRequest");
    private final static QName _SolicitudDesafioResponse_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "SolicitudDesafioResponse");
    private final static QName _CrearDesafioResponse_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "CrearDesafioResponse");
    private final static QName _AutentificarRequest_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "AutentificarRequest");
    private final static QName _AutentificarResponse_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "AutentificarResponse");
    private final static QName _CrearDesafioRequest_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "CrearDesafioRequest");
    private final static QName _ListarDesafiosResponse_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "ListarDesafiosResponse");
    private final static QName _SolicitudDesafioRequest_QNAME = new QName("http://www.bice.cl/bice-ws/seguridad/desafio/schemas", "SolicitudDesafioRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.bice.seguridad.sfa.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EstaTelefonoRegistradoRequestType }
     * 
     */
    public EstaTelefonoRegistradoRequestType createEstaTelefonoRegistradoRequestType() {
        return new EstaTelefonoRegistradoRequestType();
    }

    /**
     * Create an instance of {@link EliminaRegistroUsuarioResponseType }
     * 
     */
    public EliminaRegistroUsuarioResponseType createEliminaRegistroUsuarioResponseType() {
        return new EliminaRegistroUsuarioResponseType();
    }

    /**
     * Create an instance of {@link RegistrarUsuarioResponseType }
     * 
     */
    public RegistrarUsuarioResponseType createRegistrarUsuarioResponseType() {
        return new RegistrarUsuarioResponseType();
    }

    /**
     * Create an instance of {@link ObtenerCelularResponseType }
     * 
     */
    public ObtenerCelularResponseType createObtenerCelularResponseType() {
        return new ObtenerCelularResponseType();
    }

    /**
     * Create an instance of {@link EstaTelefonoRegistradoResponseType }
     * 
     */
    public EstaTelefonoRegistradoResponseType createEstaTelefonoRegistradoResponseType() {
        return new EstaTelefonoRegistradoResponseType();
    }

    /**
     * Create an instance of {@link EstadoSmsType }
     * 
     */
    public EstadoSmsType createEstadoSmsType() {
        return new EstadoSmsType();
    }

    /**
     * Create an instance of {@link RegistrarUsuarioRequestType }
     * 
     */
    public RegistrarUsuarioRequestType createRegistrarUsuarioRequestType() {
        return new RegistrarUsuarioRequestType();
    }

    /**
     * Create an instance of {@link EnviarSmsResponseType }
     * 
     */
    public EnviarSmsResponseType createEnviarSmsResponseType() {
        return new EnviarSmsResponseType();
    }

    /**
     * Create an instance of {@link EliminaRegistroUsuarioRequestType }
     * 
     */
    public EliminaRegistroUsuarioRequestType createEliminaRegistroUsuarioRequestType() {
        return new EliminaRegistroUsuarioRequestType();
    }

    /**
     * Create an instance of {@link EnviarSmsRequestType }
     * 
     */
    public EnviarSmsRequestType createEnviarSmsRequestType() {
        return new EnviarSmsRequestType();
    }

    /**
     * Create an instance of {@link ObtenerCelularRequestType }
     * 
     */
    public ObtenerCelularRequestType createObtenerCelularRequestType() {
        return new ObtenerCelularRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EliminaRegistroUsuarioRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "EliminaRegistroUsuarioRequest")
    public JAXBElement<EliminaRegistroUsuarioRequestType> createEliminaRegistroUsuarioRequest(EliminaRegistroUsuarioRequestType value) {
        return new JAXBElement<EliminaRegistroUsuarioRequestType>(_EliminaRegistroUsuarioRequest_QNAME, EliminaRegistroUsuarioRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistrarUsuarioRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "RegistrarUsuarioRequest")
    public JAXBElement<RegistrarUsuarioRequestType> createRegistrarUsuarioRequest(RegistrarUsuarioRequestType value) {
        return new JAXBElement<RegistrarUsuarioRequestType>(_RegistrarUsuarioRequest_QNAME, RegistrarUsuarioRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EstaTelefonoRegistradoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "EstaTelefonoRegistradoResponse")
    public JAXBElement<EstaTelefonoRegistradoResponseType> createEstaTelefonoRegistradoResponse(EstaTelefonoRegistradoResponseType value) {
        return new JAXBElement<EstaTelefonoRegistradoResponseType>(_EstaTelefonoRegistradoResponse_QNAME, EstaTelefonoRegistradoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerCelularResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "ObtenerCelularResponse")
    public JAXBElement<ObtenerCelularResponseType> createObtenerCelularResponse(ObtenerCelularResponseType value) {
        return new JAXBElement<ObtenerCelularResponseType>(_ObtenerCelularResponse_QNAME, ObtenerCelularResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistrarUsuarioResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "RegistrarUsuarioResponse")
    public JAXBElement<RegistrarUsuarioResponseType> createRegistrarUsuarioResponse(RegistrarUsuarioResponseType value) {
        return new JAXBElement<RegistrarUsuarioResponseType>(_RegistrarUsuarioResponse_QNAME, RegistrarUsuarioResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EliminaRegistroUsuarioResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "EliminaRegistroUsuarioResponse")
    public JAXBElement<EliminaRegistroUsuarioResponseType> createEliminaRegistroUsuarioResponse(EliminaRegistroUsuarioResponseType value) {
        return new JAXBElement<EliminaRegistroUsuarioResponseType>(_EliminaRegistroUsuarioResponse_QNAME, EliminaRegistroUsuarioResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EstaTelefonoRegistradoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "EstaTelefonoRegistradoRequest")
    public JAXBElement<EstaTelefonoRegistradoRequestType> createEstaTelefonoRegistradoRequest(EstaTelefonoRegistradoRequestType value) {
        return new JAXBElement<EstaTelefonoRegistradoRequestType>(_EstaTelefonoRegistradoRequest_QNAME, EstaTelefonoRegistradoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnviarSmsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "EnviarSmsResponse")
    public JAXBElement<EnviarSmsResponseType> createEnviarSmsResponse(EnviarSmsResponseType value) {
        return new JAXBElement<EnviarSmsResponseType>(_EnviarSmsResponse_QNAME, EnviarSmsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerCelularRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "ObtenerCelularRequest")
    public JAXBElement<ObtenerCelularRequestType> createObtenerCelularRequest(ObtenerCelularRequestType value) {
        return new JAXBElement<ObtenerCelularRequestType>(_ObtenerCelularRequest_QNAME, ObtenerCelularRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnviarSmsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/sms", name = "EnviarSmsRequest")
    public JAXBElement<EnviarSmsRequestType> createEnviarSmsRequest(EnviarSmsRequestType value) {
        return new JAXBElement<EnviarSmsRequestType>(_EnviarSmsRequest_QNAME, EnviarSmsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link RespuestaDesafioType }
     * 
     */
    public RespuestaDesafioType createRespuestaDesafioType() {
        return new RespuestaDesafioType();
    }

    /**
     * Create an instance of {@link ListarDesafiosRequestType }
     * 
     */
    public ListarDesafiosRequestType createListarDesafiosRequestType() {
        return new ListarDesafiosRequestType();
    }

    /**
     * Create an instance of {@link AutentificarRequestType }
     * 
     */
    public AutentificarRequestType createAutentificarRequestType() {
        return new AutentificarRequestType();
    }

    /**
     * Create an instance of {@link CrearDesafioRequestType }
     * 
     */
    public CrearDesafioRequestType createCrearDesafioRequestType() {
        return new CrearDesafioRequestType();
    }

    /**
     * Create an instance of {@link DesafioType }
     * 
     */
    public DesafioType createDesafioType() {
        return new DesafioType();
    }

    /**
     * Create an instance of {@link CoordenadasType }
     * 
     */
    public CoordenadasType createCoordenadasType() {
        return new CoordenadasType();
    }

    /**
     * Create an instance of {@link AutentificarResponseType }
     * 
     */
    public AutentificarResponseType createAutentificarResponseType() {
        return new AutentificarResponseType();
    }

    /**
     * Create an instance of {@link DesafiosListadoType }
     * 
     */
    public DesafiosListadoType createDesafiosListadoType() {
        return new DesafiosListadoType();
    }

    /**
     * Create an instance of {@link SolicitudDesafioType }
     * 
     */
    public SolicitudDesafioType createSolicitudDesafioType() {
        return new SolicitudDesafioType();
    }

    /**
     * Create an instance of {@link DesafioListadoType }
     * 
     */
    public DesafioListadoType createDesafioListadoType() {
        return new DesafioListadoType();
    }

    /**
     * Create an instance of {@link CoordenadaType }
     * 
     */
    public CoordenadaType createCoordenadaType() {
        return new CoordenadaType();
    }

    /**
     * Create an instance of {@link DesafiosType }
     * 
     */
    public DesafiosType createDesafiosType() {
        return new DesafiosType();
    }

    /**
     * Create an instance of {@link EstadoType }
     * 
     */
    public EstadoType createEstadoType() {
        return new EstadoType();
    }

    /**
     * Create an instance of {@link ListarDesafiosResponseType }
     * 
     */
    public ListarDesafiosResponseType createListarDesafiosResponseType() {
        return new ListarDesafiosResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListarDesafiosRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "ListarDesafiosRequest")
    public JAXBElement<ListarDesafiosRequestType> createListarDesafiosRequest(ListarDesafiosRequestType value) {
        return new JAXBElement<ListarDesafiosRequestType>(_ListarDesafiosRequest_QNAME, ListarDesafiosRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespuestaDesafioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "SolicitudDesafioResponse")
    public JAXBElement<RespuestaDesafioType> createSolicitudDesafioResponse(RespuestaDesafioType value) {
        return new JAXBElement<RespuestaDesafioType>(_SolicitudDesafioResponse_QNAME, RespuestaDesafioType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespuestaDesafioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "CrearDesafioResponse")
    public JAXBElement<RespuestaDesafioType> createCrearDesafioResponse(RespuestaDesafioType value) {
        return new JAXBElement<RespuestaDesafioType>(_CrearDesafioResponse_QNAME, RespuestaDesafioType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutentificarRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "AutentificarRequest")
    public JAXBElement<AutentificarRequestType> createAutentificarRequest(AutentificarRequestType value) {
        return new JAXBElement<AutentificarRequestType>(_AutentificarRequest_QNAME, AutentificarRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutentificarResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "AutentificarResponse")
    public JAXBElement<AutentificarResponseType> createAutentificarResponse(AutentificarResponseType value) {
        return new JAXBElement<AutentificarResponseType>(_AutentificarResponse_QNAME, AutentificarResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrearDesafioRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "CrearDesafioRequest")
    public JAXBElement<CrearDesafioRequestType> createCrearDesafioRequest(CrearDesafioRequestType value) {
        return new JAXBElement<CrearDesafioRequestType>(_CrearDesafioRequest_QNAME, CrearDesafioRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListarDesafiosResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "ListarDesafiosResponse")
    public JAXBElement<ListarDesafiosResponseType> createListarDesafiosResponse(ListarDesafiosResponseType value) {
        return new JAXBElement<ListarDesafiosResponseType>(_ListarDesafiosResponse_QNAME, ListarDesafiosResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitudDesafioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", name = "SolicitudDesafioRequest")
    public JAXBElement<SolicitudDesafioType> createSolicitudDesafioRequest(SolicitudDesafioType value) {
        return new JAXBElement<SolicitudDesafioType>(_SolicitudDesafioRequest_QNAME, SolicitudDesafioType.class, null, value);
    }

}
