//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:28:23 PM GMT 
//


package cl.ares.bice.seguridad.sfa.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespuestaDesafioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespuestaDesafioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Estado" type="{http://www.bice.cl/bice-ws/seguridad/desafio/schemas}EstadoType"/>
 *         &lt;element name="Desafios" type="{http://www.bice.cl/bice-ws/seguridad/desafio/schemas}DesafiosType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespuestaDesafioType", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", propOrder = {
    "estado",
    "desafios"
})
public class RespuestaDesafioType {

    @XmlElement(name = "Estado", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas", required = true)
    protected EstadoType estado;
    @XmlElement(name = "Desafios", namespace = "http://www.bice.cl/bice-ws/seguridad/desafio/schemas")
    protected DesafiosType desafios;

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoType }
     *     
     */
    public EstadoType getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoType }
     *     
     */
    public void setEstado(EstadoType value) {
        this.estado = value;
    }

    /**
     * Gets the value of the desafios property.
     * 
     * @return
     *     possible object is
     *     {@link DesafiosType }
     *     
     */
    public DesafiosType getDesafios() {
        return desafios;
    }

    /**
     * Sets the value of the desafios property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesafiosType }
     *     
     */
    public void setDesafios(DesafiosType value) {
        this.desafios = value;
    }

}
